# Generated by Django 6.0 on 2026-02-12 19:23

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AllFieldTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char_field', models.CharField(help_text='CharField', max_length=100)),
                ('text_field', models.TextField(help_text='TextField')),
                ('slug_field', models.SlugField(help_text='SlugField')),
                ('email_field', models.EmailField(help_text='EmailField', max_length=254)),
                ('url_field', models.URLField(help_text='URLField')),
                ('uuid_field', models.UUIDField(help_text='UUIDField')),
                ('int_field', models.IntegerField(help_text='IntegerField')),
                ('big_int_field', models.BigIntegerField(help_text='BigIntegerField')),
                ('small_int_field', models.SmallIntegerField(help_text='SmallIntegerField')),
                ('positive_int_field', models.PositiveIntegerField(help_text='PositiveIntegerField')),
                ('positive_small_int_field', models.PositiveSmallIntegerField(help_text='PositiveSmallIntegerField')),
                ('float_field', models.FloatField(help_text='FloatField')),
                ('decimal_field', models.DecimalField(decimal_places=2, help_text='DecimalField', max_digits=10)),
                ('bool_field', models.BooleanField(default=False, help_text='BooleanField')),
                ('date_field', models.DateField(help_text='DateField')),
                ('datetime_field', models.DateTimeField(help_text='DateTimeField')),
                ('time_field', models.TimeField(help_text='TimeField')),
                ('duration_field', models.DurationField(help_text='DurationField')),
                ('binary_field', models.BinaryField(help_text='BinaryField')),
                ('file_path_field', models.FilePathField(help_text='FilePathField', path='/tmp')),
                ('json_field', models.JSONField(default=dict, help_text='JSONField')),
                ('ip_field', models.GenericIPAddressField(help_text='GenericIPAddressField')),
            ],
        ),
        migrations.CreateModel(
            name='AntiPatternCircularRefA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AntiPatternCommaList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name', max_length=100)),
                ('tags_csv', models.TextField(blank=True, default='', help_text='Tags as comma-separated values (should be M2M)')),
                ('categories_json', models.TextField(blank=True, default='[]', help_text='Categories as JSON string (should use JSONField or M2M)')),
            ],
        ),
        migrations.CreateModel(
            name='AntiPatternFloatMoney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(help_text='Product name', max_length=100)),
                ('price_float', models.FloatField(help_text='Price as float (loses precision)')),
                ('price_decimal', models.DecimalField(decimal_places=2, help_text='Price as decimal (correct)', max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='AntiPatternGodTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Username', max_length=100)),
                ('email', models.EmailField(help_text='Email', max_length=254)),
                ('password_hash', models.CharField(help_text='Password hash', max_length=255)),
                ('first_name', models.CharField(blank=True, default='', help_text='First name', max_length=100)),
                ('last_name', models.CharField(blank=True, default='', help_text='Last name', max_length=100)),
                ('bio', models.TextField(blank=True, default='', help_text='Bio')),
                ('avatar_url', models.URLField(blank=True, default='', help_text='Avatar URL')),
                ('street', models.CharField(blank=True, default='', help_text='Street', max_length=255)),
                ('city', models.CharField(blank=True, default='', help_text='City', max_length=100)),
                ('state', models.CharField(blank=True, default='', help_text='State', max_length=100)),
                ('postal_code', models.CharField(blank=True, default='', help_text='Postal code', max_length=20)),
                ('country', models.CharField(blank=True, default='', help_text='Country', max_length=100)),
                ('theme', models.CharField(default='light', help_text='Theme', max_length=50)),
                ('language', models.CharField(default='en', help_text='Language', max_length=10)),
                ('timezone', models.CharField(default='UTC', help_text='Timezone', max_length=50)),
                ('notifications_enabled', models.BooleanField(default=True, help_text='Notifications enabled')),
                ('login_count', models.PositiveIntegerField(default=0, help_text='Login count')),
                ('last_login', models.DateTimeField(blank=True, help_text='Last login', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Updated at')),
            ],
        ),
        migrations.CreateModel(
            name='AntiPatternImplicitDefaults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('optional_name', models.CharField(blank=True, help_text='Optional name without default', max_length=100)),
                ('count', models.IntegerField(help_text='Count without default', null=True)),
                ('is_active', models.BooleanField(help_text='Is active without default', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AntiPatternNoIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(help_text='Status (frequently filtered, no index)', max_length=50)),
                ('created_date', models.DateField(help_text='Created date (frequently filtered, no index)')),
                ('external_id', models.CharField(help_text='External ID (frequently looked up, no index)', max_length=100)),
                ('priority', models.IntegerField(help_text='Priority (frequently sorted, no index)')),
            ],
        ),
        migrations.CreateModel(
            name='AntiPatternPolymorphicString',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_type', models.CharField(help_text="Parent type as string (e.g., 'article', 'book')", max_length=100)),
                ('parent_id', models.PositiveIntegerField(help_text='Parent ID')),
                ('comment', models.TextField(help_text='Comment')),
            ],
        ),
        migrations.CreateModel(
            name='AntiPatternRepeatingColumns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name', max_length=100)),
                ('phone1', models.CharField(blank=True, default='', help_text='Phone 1', max_length=20)),
                ('phone2', models.CharField(blank=True, default='', help_text='Phone 2', max_length=20)),
                ('phone3', models.CharField(blank=True, default='', help_text='Phone 3', max_length=20)),
                ('email1', models.EmailField(blank=True, default='', help_text='Email 1', max_length=254)),
                ('email2', models.EmailField(blank=True, default='', help_text='Email 2', max_length=254)),
                ('email3', models.EmailField(blank=True, default='', help_text='Email 3', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='AntiPatternSoftDelete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name', max_length=100)),
                ('data', models.TextField(help_text='Data')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Deleted at', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Article title', max_length=255)),
                ('slug', models.SlugField(help_text='URL slug', max_length=255, unique=True)),
                ('content', models.TextField(help_text='Article content')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], default='DRAFT', help_text='Article status', max_length=20)),
                ('view_count', models.PositiveIntegerField(default=0, help_text='View count')),
                ('published_at', models.DateTimeField(blank=True, help_text='Published at', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Updated at')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleWithAttachments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Author name', max_length=255)),
                ('email', models.EmailField(help_text='Email address', max_length=254, unique=True)),
                ('bio', models.TextField(blank=True, default='', help_text='Biography')),
                ('is_active', models.BooleanField(default=True, help_text='Is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created at')),
            ],
        ),
        migrations.CreateModel(
            name='BigAutoPKModel',
            fields=[
                ('id', models.BigAutoField(help_text='BigAutoField PK', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CustomPKModel',
            fields=[
                ('code', models.CharField(help_text='Custom code as primary key', max_length=20, primary_key=True, serialize=False)),
                ('description', models.TextField(help_text='Description')),
            ],
        ),
        migrations.CreateModel(
            name='EmptyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='FieldOptionsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_column', models.CharField(db_column='my_custom_column', help_text='Field with custom db_column', max_length=100)),
                ('indexed_field', models.CharField(db_index=True, help_text='Field with db_index', max_length=100)),
                ('commented_field', models.CharField(db_comment='This is a database comment', help_text='Field with db_comment', max_length=100)),
                ('validated_field', models.IntegerField(help_text='Field with validators (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('non_editable_field', models.CharField(default='readonly', editable=False, help_text='Non-editable field', max_length=100)),
                ('db_default_field', models.CharField(db_default='default_value', help_text='Field with db_default', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedFieldModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='First name', max_length=100)),
                ('last_name', models.CharField(help_text='Last name', max_length=100)),
                ('full_name', models.GeneratedField(db_persist=True, expression=django.db.models.functions.text.Concat(models.F('first_name'), models.Value(' '), models.F('last_name')), help_text='Generated full name', output_field=models.CharField(max_length=201))),
            ],
        ),
        migrations.CreateModel(
            name='ModelWithLongName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('this_is_a_very_long_field_name_that_might_cause_issues', models.CharField(help_text='This is a very long help text that describes what this field is used for in great detail', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MoreFieldTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_field', models.FileField(blank=True, help_text='FileField', null=True, upload_to='uploads/')),
                ('image_field', models.ImageField(blank=True, help_text='ImageField', null=True, upload_to='images/')),
                ('positive_big_int_field', models.PositiveBigIntegerField(default=0, help_text='PositiveBigIntegerField')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Place name', max_length=100)),
                ('address', models.CharField(help_text='Address', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Updated at')),
                ('title', models.CharField(help_text='Post title', max_length=255)),
                ('body', models.TextField(help_text='Post body')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SmallAutoPKModel',
            fields=[
                ('id', models.SmallAutoField(help_text='SmallAutoField PK', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tag name', max_length=50, unique=True)),
                ('slug', models.SlugField(help_text='URL slug', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created at')),
            ],
        ),
        migrations.CreateModel(
            name='UUIDModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID primary key', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AntiPatternCircularRefB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name', max_length=100)),
                ('ref_a', models.ForeignKey(blank=True, help_text='Reference to A (circular)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refs_from_b', to='data.antipatterncircularrefa')),
            ],
        ),
        migrations.AddField(
            model_name='antipatterncircularrefa',
            name='ref_b',
            field=models.ForeignKey(blank=True, help_text='Reference to B (circular)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refs_from_a', to='data.antipatterncircularrefb'),
        ),
        migrations.CreateModel(
            name='AntiPatternEAVAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(help_text="Entity type (e.g., 'product', 'user')", max_length=100)),
                ('entity_id', models.PositiveIntegerField(help_text='Entity ID')),
                ('attribute_name', models.CharField(help_text='Attribute name', max_length=100)),
                ('attribute_value', models.TextField(help_text='Attribute value (stored as text)')),
            ],
            options={
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='eav_entity_idx')],
            },
        ),
        migrations.CreateModel(
            name='PublishedArticle',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('data.article',),
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(help_text='Object ID')),
                ('file_name', models.CharField(help_text='File name', max_length=255)),
                ('file_url', models.URLField(help_text='File URL')),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='Uploaded at')),
                ('content_type', models.ForeignKey(help_text='Content type', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(help_text='Article author', on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='data.author'),
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Book title', max_length=255)),
                ('isbn', models.CharField(help_text='ISBN-13', max_length=13, unique=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price', max_digits=10)),
                ('published_date', models.DateField(help_text='Published date')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created at')),
                ('authors', models.ManyToManyField(help_text='Book authors', related_name='books', to='data.author')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created at')),
                ('parent', models.ForeignKey(blank=True, help_text='Parent category (self-referential)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='data.category')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Article category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='data.category'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Comment content')),
                ('is_approved', models.BooleanField(default=False, help_text='Is approved')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created at')),
                ('article', models.ForeignKey(help_text='Commented article', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='data.article')),
                ('author', models.ForeignKey(help_text='Comment author', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='data.author')),
                ('parent', models.ForeignKey(blank=True, help_text='Parent comment (for nested replies)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='data.comment')),
            ],
        ),
        migrations.CreateModel(
            name='DeprecatedForeignKeyUnique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(help_text='Nickname', max_length=100)),
                ('author', models.ForeignKey(help_text='ForeignKey with unique=True (should be OneToOneField)', on_delete=django.db.models.deletion.CASCADE, related_name='deprecated_profile', to='data.author', unique=True)),
            ],
            options={
                'verbose_name': 'Deprecated FK Unique',
            },
        ),
        migrations.CreateModel(
            name='DeprecatedUniqueTogether',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Code', max_length=50)),
                ('version', models.IntegerField(help_text='Version')),
                ('name', models.CharField(help_text='Name', max_length=100)),
            ],
            options={
                'unique_together': {('code', 'version')},
            },
        ),
        migrations.CreateModel(
            name='MetaOptionsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name', max_length=100)),
                ('code', models.CharField(help_text='Code', max_length=50)),
                ('category', models.CharField(help_text='Category', max_length=50)),
                ('sort_order', models.IntegerField(default=0, help_text='Sort order')),
                ('is_active', models.BooleanField(default=True, help_text='Is active')),
            ],
            options={
                'verbose_name': 'Meta Options Model',
                'verbose_name_plural': 'Meta Options Models',
                'db_table': 'custom_table_name',
                'ordering': ['sort_order', 'name'],
                'indexes': [models.Index(fields=['name', 'code'], name='name_code_idx'), models.Index(fields=['category'], name='category_idx')],
                'constraints': [models.UniqueConstraint(fields=('name', 'code'), name='unique_name_code'), models.CheckConstraint(condition=models.Q(('sort_order__gte', 0)), name='positive_sort_order')],
            },
        ),
        migrations.CreateModel(
            name='OnDeleteCascade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name', max_length=100)),
                ('author', models.ForeignKey(help_text='CASCADE - delete this when author is deleted', on_delete=django.db.models.deletion.CASCADE, to='data.author')),
            ],
        ),
        migrations.CreateModel(
            name='OnDeleteDoNothing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name', max_length=100)),
                ('author', models.ForeignKey(help_text='DO_NOTHING - do nothing when author is deleted (DB may error)', on_delete=django.db.models.deletion.DO_NOTHING, to='data.author')),
            ],
        ),
        migrations.CreateModel(
            name='OnDeleteProtect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name', max_length=100)),
                ('author', models.ForeignKey(help_text='PROTECT - prevent author deletion if this exists', on_delete=django.db.models.deletion.PROTECT, to='data.author')),
            ],
        ),
        migrations.CreateModel(
            name='OnDeleteSetDefault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name', max_length=100)),
                ('author', models.ForeignKey(default=None, help_text='SET_DEFAULT - set to default when author is deleted', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='data.author')),
            ],
        ),
        migrations.CreateModel(
            name='OnDeleteSetNull',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name', max_length=100)),
                ('author', models.ForeignKey(help_text='SET_NULL - set to null when author is deleted', null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.author')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('place_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='data.place')),
                ('serves_pizza', models.BooleanField(default=False, help_text='Serves pizza')),
                ('serves_pasta', models.BooleanField(default=False, help_text='Serves pasta')),
                ('rating', models.DecimalField(blank=True, decimal_places=2, help_text='Rating (0-5)', max_digits=3, null=True)),
            ],
            bases=('data.place',),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar_url', models.URLField(blank=True, default='', help_text='Avatar URL')),
                ('website', models.URLField(blank=True, default='', help_text='Website URL')),
                ('location', models.CharField(blank=True, default='', help_text='Location', max_length=100)),
                ('birth_date', models.DateField(blank=True, help_text='Birth date', null=True)),
                ('author', models.OneToOneField(help_text='Associated author', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='data.author')),
            ],
        ),
        migrations.CreateModel(
            name='BookTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relevance', models.PositiveSmallIntegerField(default=0, help_text='Relevance score')),
                ('book', models.ForeignKey(help_text='Book', on_delete=django.db.models.deletion.CASCADE, to='data.book')),
                ('tag', models.ForeignKey(help_text='Tag', on_delete=django.db.models.deletion.CASCADE, to='data.tag')),
            ],
            options={
                'unique_together': {('book', 'tag')},
            },
        ),
        migrations.AddField(
            model_name='book',
            name='tags',
            field=models.ManyToManyField(help_text='Book tags', related_name='books', through='data.BookTag', to='data.tag'),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Task title', max_length=255)),
                ('description', models.TextField(blank=True, default='', help_text='Task description')),
                ('priority', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], default=2, help_text='Task priority')),
                ('due_date', models.DateTimeField(blank=True, help_text='Due date', null=True)),
                ('completed', models.BooleanField(default=False, help_text='Is completed')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created at')),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Assigned author', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='data.author')),
            ],
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text='Action performed', max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Timestamp')),
                ('user', models.ForeignKey(help_text='User', on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ArticleTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True, help_text='Added at')),
                ('article', models.ForeignKey(help_text='Article', on_delete=django.db.models.deletion.CASCADE, to='data.article')),
                ('tag', models.ForeignKey(help_text='Tag', on_delete=django.db.models.deletion.CASCADE, to='data.tag')),
            ],
            options={
                'unique_together': {('article', 'tag')},
            },
        ),
        migrations.CreateModel(
            name='UserFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Followed at')),
                ('follower', models.ForeignKey(help_text='Follower', on_delete=django.db.models.deletion.CASCADE, related_name='following', to='data.author')),
                ('following', models.ForeignKey(help_text='Following', on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='data.author')),
            ],
            options={
                'unique_together': {('follower', 'following')},
            },
        ),
    ]
